(def circumfix_tags
	(set
		[
      {:word "TEST" {:pos "NN" :counter "1" } }
			{:word "System" {:pos "NN" :counter "1" } }
			{:word "kam" {:pos "VVFIN" :counter "1" } }
			{:word "Schulen" {:pos "NN" :counter "1" } }
			{:word "Mit" {:pos "APPR" :counter "1" } }
			{:word "Maßnahmen" {:pos "NN" :counter "1" } }
			{:word "Werk" {:pos "NN" :counter "1" } }
			{:word "Sicherheit" {:pos "NN" :counter "1" } }
			{:word "mir" {:pos "PRF" :counter "1" } }
			{:word "Ministerien" {:pos "NN" :counter "1" } }
			{:word "sonst" {:pos "ADV" :counter "1" } }
			{:word "Kulturministerium" {:pos "NN" :counter "1" } }
			{:word "Organisation" {:pos "NN" :counter "1" } }
			{:word "Kulturbüro" {:pos "NN" :counter "1" } }
			{:word "ausgesucht" {:pos "VVPP" :counter "1" } }
			{:word "ausgestorbenen" {:pos "ADJA" :counter "1" } }
			{:word "Manuskript" {:pos "NN" :counter "1" } }
			{:word "auf" {:pos "APPR" :counter "1" } }
			{:word "sehr" {:pos "ADV" :counter "1" } }
			{:word "strikt" {:pos "ADJD" :counter "1" } }
			{:word "diese" {:pos "PDAT" :counter "1" } }
			{:word "1974" {:pos "CARD" :counter "1" } }
			{:word "automatisch" {:pos "ADJD" :counter "1" } }
			{:word "Wechsel" {:pos "NN" :counter "1" } }
			{:word "enthalten" {:pos "VVINF" :counter "1" } }
			{:word "über" {:pos "APPR" :counter "1" } }
			{:word "Präsidenten-Palastes" {:pos "NN" :counter "1" } }
			{:word "Körnchen" {:pos "NN" :counter "1" } }
			{:word "ägyptisches" {:pos "ADJA" :counter "1" } }
			{:word "Radio" {:pos "NN" :counter "1" } }
			{:word "al" {:pos "NE" :counter "1" } }
			{:word "Schallplatten" {:pos "NN" :counter "1" } }
			{:word "Journalisten" {:pos "NN" :counter "1" } }
			{:word "Schulklasse" {:pos "NN" :counter "1" } }
			{:word "Mudhafar" {:pos "NE" :counter "1" } }
			{:word "einigermaßen" {:pos "ADV" :counter "1" } }
			{:word "Einzelheiten" {:pos "NN" :counter "1" } }
			{:word "so" {:pos "ADV" :counter "1" } }
			{:word "mal" {:pos "ADV" :counter "1" } }
			{:word "Untergrundzeitungen" {:pos "NN" :counter "1" } }
			{:word "oder" {:pos "KON" :counter "1" } }
			{:word "zählen" {:pos "VVFIN" :counter "1" } }
			{:word "Osten" {:pos "NN" :counter "1" } }
			{:word "Regierungsverlage" {:pos "NN" :counter "1" } }
			{:word "Da" {:pos "KOUS" :counter "1" } }
			{:word "tot" {:pos "ADJD" :counter "1" } }
			{:word "Mangel" {:pos "NN" :counter "1" } }
			{:word "Jahrhundert" {:pos "NN" :counter "1" } }
			{:word "Ministerium" {:pos "NN" :counter "1" } }
			{:word "wir" {:pos "PPER" :counter "1" } }
			{:word "Veröffentlichung" {:pos "NN" :counter "1" } }
			{:word "al-Ba'ath" {:pos "NE" :counter "1" } }
			{:word "kontrolliert" {:pos "VVPP" :counter "1" } }
			{:word "Ghawar" {:pos "NE" :counter "1" } }
			{:word "Körperschaften" {:pos "NN" :counter "1" } }
			{:word "Zensurausschüsse" {:pos "NN" :counter "1" } }
			{:word "Schreibverbot" {:pos "NN" :counter "1" } }
			{:word "Liste" {:pos "NN" :counter "1" } }
			{:word "erhältlich" {:pos "ADJD" :counter "1" } }
			{:word "Weiterhin" {:pos "ADV" :counter "1" } }
			{:word "Teile" {:pos "NN" :counter "1" } }
			{:word "erfaßt" {:pos "VVPP" :counter "1" } }
			{:word "nachweisen" {:pos "VVINF" :counter "1" } }
			{:word "an" {:pos "APPR" :counter "1" } }
			{:word "Chefredaktion" {:pos "NN" :counter "1" } }
			{:word "dabei" {:pos "PROP" :counter "1" } }
			{:word "weiteren" {:pos "ADJA" :counter "1" } }
			{:word "antwortet" {:pos "VVFIN" :counter "1" } }
			{:word "andere" {:pos "ADJA" :counter "1" } }
			{:word "Hauptstadt" {:pos "NN" :counter "1" } }
			{:word "Ägypten" {:pos "NE" :counter "1" } }
			{:word "Früher" {:pos "ADV" :counter "1" } }
			{:word "1977" {:pos "CARD" :counter "1" } }
			{:word "al-Mawqef" {:pos "NE" :counter "1" } }
			{:word "Wenn" {:pos "KOUS" :counter "1" } }
			{:word "Coup" {:pos "NN" :counter "1" } }
			{:word "bis" {:pos "APPR" :counter "1" } }
			{:word "Kino" {:pos "NN" :counter "1" } }
			{:word "Fall" {:pos "NN" :counter "1" } }
			{:word "Post" {:pos "NN" :counter "1" } }
			{:word "Ba'ath-Partei" {:pos "NN" :counter "1" } }
			{:word "Universitäten" {:pos "NN" :counter "1" } }
			{:word "verbotene" {:pos "ADJA" :counter "1" } }
			{:word "ihn" {:pos "PPER" :counter "1" } }
			{:word "Exil" {:pos "NN" :counter "1" } }
			{:word "Curricula" {:pos "NN" :counter "1" } }
			{:word "die" {:pos "PRELS" :counter "1" } }
			{:word "Schuld" {:pos "NN" :counter "1" } }
			{:word "1975" {:pos "CARD" :counter "1" } }
			{:word "künstlerischen" {:pos "ADJA" :counter "1" } }
			{:word "normalerweise" {:pos "ADV" :counter "1" } }
			{:word "Hand" {:pos "NN" :counter "1" } }
			{:word "erließ" {:pos "VVFIN" :counter "1" } }
			{:word "`" {:pos "$(" :counter "1" } }
			{:word "unterdrückender" {:pos "ADJA" :counter "1" } }
			{:word "Kritisches" {:pos "NN" :counter "1" } }
			{:word "also" {:pos "ADV" :counter "1" } }
			{:word ":" {:pos "$." :counter "1" } }
			{:word "Aktivitäten" {:pos "NN" :counter "1" } }
			{:word "weiter" {:pos "ADV" :counter "1" } }
			{:word "Schriftstellerverband" {:pos "NN" :counter "1" } }
			{:word "berühmten" {:pos "ADJA" :counter "1" } }
			{:word "Drucklegung" {:pos "NN" :counter "1" } }
			{:word "gelten" {:pos "VVINF" :counter "1" } }
			{:word "prominenten" {:pos "ADJA" :counter "1" } }
			{:word "als" {:pos "KOKOM" :counter "1" } }
			{:word "wurde" {:pos "VAFIN" :counter "1" } }
			{:word "London" {:pos "NE" :counter "1" } }
			{:word "was" {:pos "PWS" :counter "1" } }
			{:word "Videokassetten" {:pos "NN" :counter "1" } }
			{:word "verboten" {:pos "VVPP" :counter "1" } }
			{:word "ausdrückliche" {:pos "ADJA" :counter "1" } }
			{:word "schreiben" {:pos "VVFIN" :counter "1" } }
			{:word "verbotener" {:pos "ADJA" :counter "1" } }
			{:word "fragwürdig" {:pos "ADJD" :counter "1" } }
			{:word "geschleust" {:pos "VVPP" :counter "1" } }
			{:word "jedes" {:pos "PIDAT" :counter "1" } }
			{:word "Hälfte" {:pos "NN" :counter "1" } }
			{:word "al-Thawra" {:pos "NE" :counter "1" } }
			{:word "nirgends" {:pos "ADV" :counter "1" } }
			{:word "Gesetz" {:pos "NN" :counter "1" } }
			{:word "angesehen" {:pos "VVPP" :counter "1" } }
			{:word "Arten" {:pos "NN" :counter "1" } }
			{:word "al-Marifa" {:pos "NE" :counter "1" } }
			{:word "mitgenommen" {:pos "VVPP" :counter "1" } }
			{:word "publizieren" {:pos "VVFIN" :counter "1" } }
			{:word "arabischsprachige" {:pos "ADJA" :counter "1" } }
			{:word "wichtige" {:pos "ADJA" :counter "1" } }
			{:word "oft" {:pos "ADV" :counter "1" } }
			{:word "Zensurapparat" {:pos "NN" :counter "1" } }
			{:word "Grenze" {:pos "NN" :counter "1" } }
			{:word "kriegte" {:pos "VVFIN" :counter "1" } }
			{:word "al-Nawab" {:pos "NE" :counter "1" } }
			{:word "private" {:pos "ADJA" :counter "1" } }
			{:word "sein" {:pos "VAINF" :counter "1" } }
			{:word "Nummern" {:pos "NN" :counter "1" } }
			{:word "verschiedenen" {:pos "ADJA" :counter "1" } }
			{:word "Iran" {:pos "NE" :counter "1" } }
			{:word "kann" {:pos "VMFIN" :counter "1" } }
			{:word "solange" {:pos "KOUS" :counter "1" } }
			{:word "syrischer" {:pos "ADJA" :counter "1" } }
			{:word "diversen" {:pos "ADJA" :counter "1" } }
			{:word "Wirkliche" {:pos "ADJA" :counter "1" } }
			{:word "religiöse" {:pos "ADJA" :counter "1" } }
			{:word "jedesmal" {:pos "ADV" :counter "1" } }
			{:word "Dies" {:pos "PDS" :counter "1" } }
			{:word "damals" {:pos "ADV" :counter "1" } }
			{:word "Partei" {:pos "NN" :counter "1" } }
			{:word "freigibt" {:pos "VVFIN" :counter "1" } }
			{:word "viel" {:pos "PIS" :counter "1" } }
			{:word "per" {:pos "APPR" :counter "1" } }
			{:word "zu" {:pos "APPR" :counter "1" } }
			{:word "Stempel" {:pos "NN" :counter "1" } }
			{:word "Verlage" {:pos "NN" :counter "1" } }
			{:word "vorher" {:pos "ADV" :counter "1" } }
			{:word "alle" {:pos "PIS" :counter "1" } }
			{:word "libanesischen" {:pos "ADJA" :counter "1" } }
			{:word "derweil" {:pos "ADV" :counter "1" } }
			{:word "Heutzutage" {:pos "ADV" :counter "1" } }
			{:word "sind" {:pos "VAFIN" :counter "1" } }
			{:word "Lager" {:pos "NN" :counter "1" } }
			{:word "wie" {:pos "KOKOM" :counter "1" } }
			{:word "einzelnen" {:pos "ADJA" :counter "1" } }
			{:word "entsprechen" {:pos "VVFIN" :counter "1" } }
			{:word "alt" {:pos "ADJD" :counter "1" } }
			{:word "Organ" {:pos "NN" :counter "1" } }
			{:word "manchen" {:pos "PIAT" :counter "1" } }
			{:word "entweder" {:pos "KON" :counter "1" } }
			{:word "denn" {:pos "KON" :counter "1" } }
			{:word "Schah" {:pos "NN" :counter "1" } }
			{:word "Erlaubnis" {:pos "NN" :counter "1" } }
			{:word "angelegt" {:pos "VVPP" :counter "1" } }
			{:word "kritische" {:pos "ADJA" :counter "1" } }
			{:word "noch" {:pos "ADV" :counter "1" } }
			{:word "Verkauf" {:pos "NN" :counter "1" } }
			{:word "angeführt" {:pos "VVPP" :counter "1" } }
			{:word "neue" {:pos "ADJA" :counter "1" } }
			{:word "solch" {:pos "PIDAT" :counter "1" } }
			{:word "Syriens" {:pos "NE" :counter "1" } }
			{:word "Resultat" {:pos "NN" :counter "1" } }
			{:word "Textes" {:pos "NN" :counter "1" } }
			{:word "wurden" {:pos "VAFIN" :counter "1" } }
			{:word "Zeit" {:pos "NN" :counter "1" } }
			{:word ")" {:pos "$(" :counter "1" } }
			{:word """ {:pos "$(" :counter "1" } }
			{:word "Regierung" {:pos "NN" :counter "1" } }
			{:word "Exodus" {:pos "NN" :counter "1" } }
			{:word "jedoch" {:pos "ADV" :counter "1" } }
			{:word "Imam" {:pos "NE" :counter "1" } }
			{:word "al-Toushi" {:pos "NE" :counter "1" } }
			{:word "es" {:pos "PPER" :counter "1" } }
			{:word "Nachrichten" {:pos "NN" :counter "1" } }
			{:word "Ansicht" {:pos "NN" :counter "1" } }
			{:word "Land" {:pos "NN" :counter "1" } }
			{:word "Lazikia" {:pos "NE" :counter "1" } }
			{:word "politische" {:pos "ADJA" :counter "1" } }
			{:word "gerade" {:pos "ADV" :counter "1" } }
			{:word "Herren" {:pos "NN" :counter "1" } }
			{:word "überhaupt" {:pos "ADV" :counter "1" } }
			{:word "Kulturmagazins" {:pos "NN" :counter "1" } }
			{:word "nicht" {:pos "PTKNEG" :counter "1" } }
			{:word "Bescheinigung" {:pos "NN" :counter "1" } }
			{:word "Zeitschrift" {:pos "NN" :counter "1" } }
			{:word "Beispiel" {:pos "NN" :counter "1" } }
			{:word "." {:pos "$." :counter "1" } }
			{:word "erlauben" {:pos "VVFIN" :counter "1" } }
			{:word "Schuldirektoren" {:pos "NN" :counter "1" } }
			{:word "Einfuhr" {:pos "NN" :counter "1" } }
			{:word "aber" {:pos "KON" :counter "1" } }
			{:word "herausgeben" {:pos "VVFIN" :counter "1" } }
			{:word "verschlechtert" {:pos "VVPP" :counter "1" } }
			{:word "ausgeführt" {:pos "VVPP" :counter "1" } }
			{:word "Veränderungen" {:pos "NN" :counter "1" } }
			{:word "gehen" {:pos "VVFIN" :counter "1" } }
			{:word "arbeitete" {:pos "VVFIN" :counter "1" } }
			{:word "daraufhin" {:pos "PROP" :counter "1" } }
			{:word "ausfüllen" {:pos "VVFIN" :counter "1" } }
			{:word "Artikel" {:pos "NN" :counter "1" } }
			{:word "wollen" {:pos "VMFIN" :counter "1" } }
			{:word "stammende" {:pos "ADJA" :counter "1" } }
			{:word "Dieses" {:pos "PDAT" :counter "1" } }
			{:word "Parteimann" {:pos "NN" :counter "1" } }
			{:word "Akten" {:pos "NN" :counter "1" } }
			{:word "begann" {:pos "VVFIN" :counter "1" } }
			{:word "einem" {:pos "ART" :counter "1" } }
			{:word "bevor" {:pos "KOUS" :counter "1" } }
			{:word "BBC-Worldservice" {:pos "NE" :counter "1" } }
			{:word "sinnlos" {:pos "ADJD" :counter "1" } }
			{:word "wird" {:pos "VAFIN" :counter "1" } }
			{:word "Am" {:pos "APPRART" :counter "1" } }
			{:word "Schreibtischarbeit" {:pos "NN" :counter "1" } }
			{:word "'" {:pos "$(" :counter "1" } }
			{:word "fertige" {:pos "ADJA" :counter "1" } }
			{:word "Obwohl" {:pos "KOUS" :counter "1" } }
			{:word "Alles" {:pos "PIS" :counter "1" } }
			{:word "1947" {:pos "CARD" :counter "1" } }
			{:word "Wahrheit" {:pos "NN" :counter "1" } }
			{:word "Städten" {:pos "NN" :counter "1" } }
			{:word "seit" {:pos "APPR" :counter "1" } }
			{:word "Stimme" {:pos "NN" :counter "1" } }
			{:word "fällt" {:pos "VVFIN" :counter "1" } }
			{:word "geschickt" {:pos "VVPP" :counter "1" } }
			{:word "weiterzuarbeiten" {:pos "VVIZU" :counter "1" } }
			{:word "25" {:pos "CARD" :counter "1" } }
			{:word "Stücke" {:pos "NN" :counter "1" } }
			{:word "internen" {:pos "ADJA" :counter "1" } }
			{:word "Nummer" {:pos "NN" :counter "1" } }
			{:word "Spezies" {:pos "NN" :counter "1" } }
			{:word "Text" {:pos "NN" :counter "1" } }
			{:word "sogar" {:pos "ADV" :counter "1" } }
			{:word "Behörden" {:pos "NN" :counter "1" } }
			{:word "Periodika" {:pos "NN" :counter "1" } }
			{:word "irakischen" {:pos "ADJA" :counter "1" } }
			{:word "angeht" {:pos "VVFIN" :counter "1" } }
			{:word "Repräsentation" {:pos "NN" :counter "1" } }
			{:word "offizielle" {:pos "ADJA" :counter "1" } }
			{:word "einzelner" {:pos "NN" :counter "1" } }
			{:word "jede" {:pos "PIDAT" :counter "1" } }
			{:word "Jahren" {:pos "NN" :counter "1" } }
			{:word "einfach" {:pos "ADV" :counter "1" } }
			{:word "anhält" {:pos "VVFIN" :counter "1" } }
			{:word "Wenig" {:pos "ADV" :counter "1" } }
			{:word "Präsidenten" {:pos "NN" :counter "1" } }
			{:word "Kontroll-" {:pos "TRUNC" :counter "1" } }
			{:word "jedem" {:pos "PIDAT" :counter "1" } }
			{:word "Schlüsselpositionen" {:pos "NN" :counter "1" } }
			{:word "gehören" {:pos "VVFIN" :counter "1" } }
			{:word "Buchhandlungen" {:pos "NN" :counter "1" } }
			{:word "Verhältnisse" {:pos "NN" :counter "1" } }
			{:word "Ausreise" {:pos "NN" :counter "1" } }
			{:word "bringen" {:pos "VVINF" :counter "1" } }
			{:word "Richtlinien" {:pos "NN" :counter "1" } }
			{:word "zumindest" {:pos "ADV" :counter "1" } }
			{:word "sowohl" {:pos "KON" :counter "1" } }
			{:word "mehr" {:pos "ADV" :counter "1" } }
			{:word "zudem" {:pos "PROP" :counter "1" } }
			{:word "in" {:pos "APPR" :counter "1" } }
			{:word "ein" {:pos "ART" :counter "1" } }
			{:word "Sie" {:pos "PPER" :counter "1" } }
			{:word "Westen" {:pos "NN" :counter "1" } }
			{:word "äußern" {:pos "VVFIN" :counter "1" } }
			{:word "ihrerseits" {:pos "ADV" :counter "1" } }
			{:word "Lieder" {:pos "NN" :counter "1" } }
			{:word "Schriftstellergewerkschaft" {:pos "NN" :counter "1" } }
			{:word "Kinder" {:pos "NN" :counter "1" } }
			{:word "tat" {:pos "VVFIN" :counter "1" } }
			{:word "Willkür" {:pos "NN" :counter "1" } }
			{:word "Normalerweise" {:pos "ADV" :counter "1" } }
			{:word "allen" {:pos "PIDAT" :counter "1" } }
			{:word "Eine" {:pos "ART" :counter "1" } }
			{:word "freigegeben" {:pos "VVPP" :counter "1" } }
			{:word "Volk" {:pos "NN" :counter "1" } }
			{:word "Spionen" {:pos "NN" :counter "1" } }
			{:word "lassen" {:pos "VVINF" :counter "1" } }
			{:word "darin" {:pos "PROP" :counter "1" } }
			{:word "vier" {:pos "CARD" :counter "1" } }
			{:word "abgesegnet" {:pos "VVPP" :counter "1" } }
			{:word "Wer" {:pos "PWS" :counter "1" } }
			{:word "gelegentlich" {:pos "ADJD" :counter "1" } }
			{:word "wiederum" {:pos "ADV" :counter "1" } }
			{:word "Manchmal" {:pos "ADV" :counter "1" } }
			{:word "Falls" {:pos "KOUS" :counter "1" } }
			{:word "Import" {:pos "NN" :counter "1" } }
			{:word "Schauspieler" {:pos "NN" :counter "1" } }
			{:word "ihrem" {:pos "PPOSAT" :counter "1" } }
			{:word "zur" {:pos "APPRART" :counter "1" } }
			{:word "Regierungen" {:pos "NN" :counter "1" } }
			{:word "zusammen" {:pos "ADV" :counter "1" } }
			{:word "Um" {:pos "KOUI" :counter "1" } }
			{:word "gestempelte" {:pos "ADJA" :counter "1" } }
			{:word "erhält" {:pos "VVFIN" :counter "1" } }
			{:word "Gedrucktes" {:pos "NN" :counter "1" } }
			{:word "ist" {:pos "VAFIN" :counter "1" } }
			{:word "bekommt" {:pos "VVFIN" :counter "1" } }
			{:word "entgeht" {:pos "VVFIN" :counter "1" } }
			{:word "arabischen" {:pos "ADJA" :counter "1" } }
			{:word "Zeitschriften" {:pos "NN" :counter "1" } }
			{:word "unerwünschten" {:pos "ADJA" :counter "1" } }
			{:word "Vorlage" {:pos "NN" :counter "1" } }
			{:word "alles" {:pos "PIS" :counter "1" } }
			{:word "ebenfalls" {:pos "ADV" :counter "1" } }
			{:word "Dreherlaubnis" {:pos "NN" :counter "1" } }
			{:word "sicherzugehen" {:pos "VVIZU" :counter "1" } }
			{:word "Beruf" {:pos "NN" :counter "1" } }
			{:word "Films" {:pos "NN" :counter "1" } }
			{:word "heißt" {:pos "VVFIN" :counter "1" } }
			{:word "Filmen" {:pos "NN" :counter "1" } }
			{:word "Es" {:pos "PPER" :counter "1" } }
			{:word "Tonbänder" {:pos "NN" :counter "1" } }
			{:word "staatsbeleidigend" {:pos "ADJD" :counter "1" } }
			{:word "schrieb" {:pos "VVFIN" :counter "1" } }
			{:word "überall" {:pos "ADV" :counter "1" } }
			{:word "Freitagspredigt" {:pos "NN" :counter "1" } }
			{:word "entsprechenden" {:pos "ADJA" :counter "1" } }
			{:word "Schriftstellers" {:pos "NN" :counter "1" } }
			{:word "dem" {:pos "ART" :counter "1" } }
			{:word "Gehalt" {:pos "NN" :counter "1" } }
			{:word "müssen" {:pos "VMFIN" :counter "1" } }
			{:word "Monte" {:pos "NE" :counter "1" } }
			{:word "Bruder" {:pos "NN" :counter "1" } }
			{:word "Monopol" {:pos "NN" :counter "1" } }
			{:word "Hause" {:pos "NN" :counter "1" } }
			{:word "darauf" {:pos "PROP" :counter "1" } }
			{:word "durchaus" {:pos "ADV" :counter "1" } }
			{:word "kontrollieren" {:pos "VVFIN" :counter "1" } }
			{:word "beschlagnahmt" {:pos "VVPP" :counter "1" } }
			{:word "Dichters" {:pos "NN" :counter "1" } }
			{:word "denen" {:pos "PRELS" :counter "1" } }
			{:word "schriftlich" {:pos "ADJD" :counter "1" } }
			{:word "erscheinen" {:pos "VVFIN" :counter "1" } }
			{:word "das" {:pos "PDS" :counter "1" } }
			{:word "Periodikum" {:pos "NN" :counter "1" } }
			{:word "Vertrieb" {:pos "NN" :counter "1" } }
			{:word "Kinderzeitschrift" {:pos "NN" :counter "1" } }
			{:word "für" {:pos "APPR" :counter "1" } }
			{:word ";" {:pos "$." :counter "1" } }
			{:word "Job" {:pos "NN" :counter "1" } }
			{:word "Antragsformular" {:pos "NN" :counter "1" } }
			{:word "Lehrkörper" {:pos "NN" :counter "1" } }
			{:word "wo" {:pos "PWAV" :counter "1" } }
			{:word "Privatpersonen" {:pos "NN" :counter "1" } }
			{:word "darf" {:pos "VMFIN" :counter "1" } }
			{:word "Zum" {:pos "APPRART" :counter "1" } }
			{:word "gilt" {:pos "VVFIN" :counter "1" } }
			{:word "Lehrenden" {:pos "NN" :counter "1" } }
			{:word "-" {:pos "$(" :counter "1" } }
			{:word "Hafiz" {:pos "NE" :counter "1" } }
			{:word "Buch" {:pos "NN" :counter "1" } }
			{:word "1963" {:pos "CARD" :counter "1" } }
			{:word "abdrucken" {:pos "VVINF" :counter "1" } }
			{:word "Diese" {:pos "PDAT" :counter "1" } }
			{:word "Tishreen" {:pos "NE" :counter "1" } }
			{:word "verantwortlich" {:pos "ADJD" :counter "1" } }
			{:word "Ende" {:pos "NN" :counter "1" } }
			{:word "tanzte" {:pos "VVFIN" :counter "1" } }
			{:word "verbietet" {:pos "VVFIN" :counter "1" } }
			{:word "gegen" {:pos "APPR" :counter "1" } }
			{:word "erschienen" {:pos "VVPP" :counter "1" } }
			{:word "schickt" {:pos "VVFIN" :counter "1" } }
			{:word "umfassenden" {:pos "ADJA" :counter "1" } }
			{:word "Housni" {:pos "NE" :counter "1" } }
			{:word "Bücher" {:pos "NN" :counter "1" } }
			{:word "Sparten" {:pos "NN" :counter "1" } }
			{:word "Einige" {:pos "PIAT" :counter "1" } }
			{:word "indem" {:pos "KOUS" :counter "1" } }
			{:word "gerufen" {:pos "VVPP" :counter "1" } }
			{:word "Redakteure" {:pos "NN" :counter "1" } }
			{:word "Golf-Staaten" {:pos "NN" :counter "1" } }
			{:word "Europa" {:pos "NE" :counter "1" } }
			{:word "gibt" {:pos "VVFIN" :counter "1" } }
			{:word "zurück" {:pos "PTKVZ" :counter "1" } }
			{:word "inzwischen" {:pos "ADV" :counter "1" } }
			{:word "Staatsstruktur" {:pos "NN" :counter "1" } }
			{:word "eines" {:pos "ART" :counter "1" } }
			{:word "können" {:pos "VMFIN" :counter "1" } }
			{:word "aufgrund" {:pos "APPR" :counter "1" } }
			{:word "seine" {:pos "PPOSAT" :counter "1" } }
			{:word "dieses" {:pos "PDAT" :counter "1" } }
			{:word "sofort" {:pos "ADV" :counter "1" } }
			{:word "Angeklagte" {:pos "NN" :counter "1" } }
			{:word "Entscheidung" {:pos "NN" :counter "1" } }
			{:word "hört" {:pos "VVFIN" :counter "1" } }
			{:word "keine" {:pos "PIAT" :counter "1" } }
			{:word "Reihe" {:pos "NN" :counter "1" } }
			{:word "verlor" {:pos "VVFIN" :counter "1" } }
			{:word "informiert" {:pos "VVPP" :counter "1" } }
			{:word "neben" {:pos "APPR" :counter "1" } }
			{:word "Geheimdienst" {:pos "NN" :counter "1" } }
			{:word "erscheint" {:pos "VVFIN" :counter "1" } }
			{:word "Zustand" {:pos "NN" :counter "1" } }
			{:word "sagen" {:pos "VVINF" :counter "1" } }
			{:word "werden" {:pos "VAINF" :counter "1" } }
			{:word "arbeitet" {:pos "VVFIN" :counter "1" } }
			{:word "selbst" {:pos "ADV" :counter "1" } }
			{:word "weitergeleitet" {:pos "VVPP" :counter "1" } }
			{:word "Situation" {:pos "NN" :counter "1" } }
			{:word "tatsächlich" {:pos "ADV" :counter "1" } }
			{:word "Freunde" {:pos "NN" :counter "1" } }
			{:word "durchgesiebt" {:pos "VVPP" :counter "1" } }
			{:word "Zensors" {:pos "NN" :counter "1" } }
			{:word "direkt" {:pos "ADJD" :counter "1" } }
			{:word "verhört" {:pos "VVPP" :counter "1" } }
			{:word "erlangen" {:pos "VVINF" :counter "1" } }
			{:word "neuen" {:pos "ADJA" :counter "1" } }
			{:word "Amerikas" {:pos "NE" :counter "1" } }
			{:word "Syrien" {:pos "NE" :counter "1" } }
			{:word "niemand" {:pos "PIS" :counter "1" } }
			{:word "Scheikh" {:pos "NN" :counter "1" } }
			{:word "1970" {:pos "CARD" :counter "1" } }
			{:word "Die" {:pos "ART" :counter "1" } }
			{:word "Nach" {:pos "APPR" :counter "1" } }
			{:word "(" {:pos "$(" :counter "1" } }
			{:word "gegeben" {:pos "VVPP" :counter "1" } }
			{:word "Staatsangestellten" {:pos "NN" :counter "1" } }
			{:word "ganz" {:pos "ADV" :counter "1" } }
			{:word "haben" {:pos "VAINF" :counter "1" } }
			{:word "regierenden" {:pos "ADJA" :counter "1" } }
			{:word "Informationsministerium" {:pos "NN" :counter "1" } }
			{:word "Nachdem" {:pos "KOUS" :counter "1" } }
			{:word "gesamte" {:pos "ADJA" :counter "1" } }
			{:word "man" {:pos "PIS" :counter "1" } }
			{:word "Carlo" {:pos "NE" :counter "1" } }
			{:word "Schulwechsel" {:pos "NN" :counter "1" } }
			{:word "aufgeben" {:pos "VVINF" :counter "1" } }
			{:word "Bühne" {:pos "NN" :counter "1" } }
			{:word "Zeitung" {:pos "NN" :counter "1" } }
			{:word "Universitätsabschluß" {:pos "NN" :counter "1" } }
			{:word "Film" {:pos "NN" :counter "1" } }
			{:word "Armee" {:pos "NN" :counter "1" } }
			{:word "Generation" {:pos "NN" :counter "1" } }
			{:word "Zensurbüro" {:pos "NN" :counter "1" } }
			{:word "Das" {:pos "ART" :counter "1" } }
			{:word "Mitglied" {:pos "NN" :counter "1" } }
			{:word "beispielsweise" {:pos "ADV" :counter "1" } }
			{:word "bisher" {:pos "ADV" :counter "1" } }
			{:word "vorliegt" {:pos "VVFIN" :counter "1" } }
			{:word "schleppen" {:pos "VVFIN" :counter "1" } }
			{:word "dieser" {:pos "PDAT" :counter "1" } }
			{:word "mich" {:pos "PPER" :counter "1" } }
			{:word "Coups" {:pos "NN" :counter "1" } }
			{:word "Gedruckte" {:pos "NN" :counter "1" } }
			{:word "syrische" {:pos "ADJA" :counter "1" } }
			{:word "zum" {:pos "APPRART" :counter "1" } }
			{:word "um" {:pos "KOUI" :counter "1" } }
			{:word "hatte" {:pos "VAFIN" :counter "1" } }
			{:word "Was" {:pos "PWS" :counter "1" } }
			{:word "vorlegen" {:pos "VVFIN" :counter "1" } }
			{:word "Tatsachen" {:pos "NN" :counter "1" } }
			{:word "Menschen" {:pos "NN" :counter "1" } }
			{:word "dessen" {:pos "PRELAT" :counter "1" } }
			{:word "Dastour" {:pos "NE" :counter "1" } }
			{:word "bleiben" {:pos "VVINF" :counter "1" } }
			{:word "nur" {:pos "ADV" :counter "1" } }
			{:word "kritisieren" {:pos "VVFIN" :counter "1" } }
			{:word "fünf" {:pos "CARD" :counter "1" } }
			{:word "herausgegeben" {:pos "VVPP" :counter "1" } }
			{:word "sie" {:pos "PPER" :counter "1" } }
			{:word "Innenministerium" {:pos "NN" :counter "1" } }
			{:word "Verse" {:pos "NN" :counter "1" } }
			{:word "zwar" {:pos "ADV" :counter "1" } }
			{:word "bedeutete" {:pos "VVFIN" :counter "1" } }
			{:word "betrifft" {:pos "VVFIN" :counter "1" } }
			{:word "Zensur-Komitees" {:pos "NN" :counter "1" } }
			{:word "nachdem" {:pos "KOUS" :counter "1" } }
			{:word "mit" {:pos "APPR" :counter "1" } }
			{:word "An" {:pos "APPR" :counter "1" } }
			{:word "Nahen" {:pos "ADJA" :counter "1" } }
			{:word "mein" {:pos "PPOSAT" :counter "1" } }
			{:word "Fernsehen" {:pos "NN" :counter "1" } }
			{:word "blieb" {:pos "VVFIN" :counter "1" } }
			{:word "versuchen" {:pos "VVFIN" :counter "1" } }
			{:word "Von" {:pos "APPR" :counter "1" } }
			{:word "jeder" {:pos "PIDAT" :counter "1" } }
			{:word "Bemerkungen" {:pos "NN" :counter "1" } }
			{:word "aufgerufen" {:pos "VVPP" :counter "1" } }
			{:word "Dennoch" {:pos "ADV" :counter "1" } }
			{:word "ob" {:pos "KOUS" :counter "1" } }
			{:word "beziehungsweise" {:pos "KON" :counter "1" } }
			{:word "Leute" {:pos "NN" :counter "1" } }
			{:word "hat" {:pos "VAFIN" :counter "1" } }
			{:word "Chefredakteur" {:pos "NN" :counter "1" } }
			{:word "Zensur" {:pos "NN" :counter "1" } }
			{:word "politischen" {:pos "ADJA" :counter "1" } }
			{:word "Wochenzeitschrift" {:pos "NN" :counter "1" } }
			{:word "ihren" {:pos "PPOSAT" :counter "1" } }
			{:word "Publikationen" {:pos "NN" :counter "1" } }
			{:word "Schwierigkeit" {:pos "NN" :counter "1" } }
			{:word "Geheimdienstes" {:pos "NN" :counter "1" } }
			{:word "außerhalb" {:pos "APPR" :counter "1" } }
			{:word "sorgfältig" {:pos "ADJD" :counter "1" } }
			{:word "auch" {:pos "ADV" :counter "1" } }
			{:word "und" {:pos "KON" :counter "1" } }
			{:word "ausgestorbene" {:pos "ADJA" :counter "1" } }
			{:word "ehemaligen" {:pos "ADJA" :counter "1" } }
			{:word "aus" {:pos "APPR" :counter "1" } }
			{:word "al-Assad" {:pos "NE" :counter "1" } }
			{:word "ausländische" {:pos "ADJA" :counter "1" } }
			{:word "geht" {:pos "VVFIN" :counter "1" } }
			{:word "Zensor" {:pos "NN" :counter "1" } }
			{:word "eingeführt" {:pos "VVPP" :counter "1" } }
			{:word "Angelegenheiten" {:pos "NN" :counter "1" } }
			{:word "vorgelegen" {:pos "VVPP" :counter "1" } }
			{:word "1979" {:pos "CARD" :counter "1" } }
			{:word "Kolumne" {:pos "NN" :counter "1" } }
			{:word "gestempelt" {:pos "VVPP" :counter "1" } }
			{:word "privater" {:pos "ADJA" :counter "1" } }
			{:word "dann" {:pos "ADV" :counter "1" } }
			{:word "daß" {:pos "KOUS" :counter "1" } }
			{:word "Innenministeriums" {:pos "NN" :counter "1" } }
			{:word "letzten" {:pos "ADJA" :counter "1" } }
			{:word "al-Safir" {:pos "NE" :counter "1" } }
			{:word "Kunst" {:pos "NN" :counter "1" } }
			{:word "gehalten" {:pos "VVPP" :counter "1" } }
			{:word "Zeilen" {:pos "NN" :counter "1" } }
			{:word "mußte" {:pos "VMFIN" :counter "1" } }
			{:word "gekleidete" {:pos "ADJA" :counter "1" } }
			{:word "Mitgliedern" {:pos "NN" :counter "1" } }
			{:word "aufgegeben" {:pos "VVPP" :counter "1" } }
			{:word "Titeln" {:pos "NN" :counter "1" } }
			{:word "heute" {:pos "ADV" :counter "1" } }
			{:word "verloren" {:pos "VVPP" :counter "1" } }
			{:word "Regionale" {:pos "ADJA" :counter "1" } }
			{:word "wissenschaftliche" {:pos "ADJA" :counter "1" } }
			{:word "nach" {:pos "APPR" :counter "1" } }
			{:word "Filme" {:pos "NN" :counter "1" } }
			{:word "zivil" {:pos "ADJD" :counter "1" } }
			{:word "einer" {:pos "ART" :counter "1" } }
			{:word "dort" {:pos "ADV" :counter "1" } }
			{:word "umgekehrt" {:pos "ADJD" :counter "1" } }
			{:word "stellt" {:pos "VVFIN" :counter "1" } }
			{:word "Bruch" {:pos "NN" :counter "1" } }
			{:word "eine" {:pos "ART" :counter "1" } }
			{:word "Allgemeinen" {:pos "ADJA" :counter "1" } }
			{:word "Scripte" {:pos "NN" :counter "1" } }
			{:word "Aleppo" {:pos "NE" :counter "1" } }
			{:word "regelmäßig" {:pos "ADJD" :counter "1" } }
			{:word "In" {:pos "APPR" :counter "1" } }
			{:word "Der" {:pos "ART" :counter "1" } }
			{:word "damit" {:pos "KOUS" :counter "1" } }
			{:word "wenn" {:pos "KOUS" :counter "1" } }
			{:word "," {:pos "$," :counter "1" } }
			{:word "einige" {:pos "PIAT" :counter "1" } }
			{:word "ersten" {:pos "ADJA" :counter "1" } }
			{:word "Zusammenstellung" {:pos "NN" :counter "1" } }
			{:word "kennen" {:pos "VVFIN" :counter "1" } }
			{:word "Man" {:pos "PIS" :counter "1" } }
			{:word "Abteilung" {:pos "NN" :counter "1" } }
			{:word "publiziert" {:pos "VVPP" :counter "1" } }
			{:word "bewerben" {:pos "VVINF" :counter "1" } }
			{:word "al-Zaim" {:pos "NE" :counter "1" } }
			{:word "Kollegen" {:pos "NN" :counter "1" } }
			{:word "gebracht" {:pos "VVPP" :counter "1" } }
			{:word "bei" {:pos "APPR" :counter "1" } }
			{:word "einmal" {:pos "ADV" :counter "1" } }
			{:word "Ich" {:pos "PPER" :counter "1" } }
			{:word "ständig" {:pos "ADJD" :counter "1" } }
			{:word "gar" {:pos "ADV" :counter "1" } }
			{:word "Überregionale" {:pos "ADJA" :counter "1" } }
			{:word "des" {:pos "ART" :counter "1" } }
			{:word "möchte" {:pos "VMFIN" :counter "1" } }
			{:word "Ausländische" {:pos "ADJA" :counter "1" } }
			{:word "Bibliothek" {:pos "NN" :counter "1" } }
			{:word "stehen" {:pos "VVINF" :counter "1" } }
			{:word "Abdrucks" {:pos "NN" :counter "1" } }
			{:word "revolutionär" {:pos "ADJD" :counter "1" } }
			{:word "arabische" {:pos "ADJA" :counter "1" } }
			{:word "Ebenso" {:pos "ADV" :counter "1" } }
			{:word "worden" {:pos "VAPP" :counter "1" } }
			{:word "gemacht" {:pos "VVPP" :counter "1" } }
			{:word "produziert" {:pos "VVPP" :counter "1" } }
			{:word "Solange" {:pos "KOUS" :counter "1" } }
			{:word "den" {:pos "ART" :counter "1" } }
			{:word "einzelne" {:pos "ADJA" :counter "1" } }
			{:word "unters" {:pos "APPRART" :counter "1" } }
			{:word "Programme" {:pos "NN" :counter "1" } }
			{:word "vorgelegt" {:pos "VVPP" :counter "1" } }
			{:word "wollte" {:pos "VMFIN" :counter "1" } }
			{:word "im" {:pos "APPRART" :counter "1" } }
			{:word "ausgedehnt" {:pos "VVPP" :counter "1" } }
			{:word "Kein" {:pos "PIAT" :counter "1" } }
			{:word "Ausgabe" {:pos "NN" :counter "1" } }
			{:word "durch" {:pos "APPR" :counter "1" } }
			{:word "leben" {:pos "VVFIN" :counter "1" } }
			{:word "halboffiziellen" {:pos "ADJA" :counter "1" } }
			{:word "Verbot" {:pos "NN" :counter "1" } }
			{:word "Filmzensur-Ausschüsse" {:pos "NN" :counter "1" } }
			{:word "wieder" {:pos "ADV" :counter "1" } }
			{:word "allgemeinen" {:pos "NN" :counter "1" } }
			{:word "da" {:pos "KOUS" :counter "1" } }
			{:word "staatliches" {:pos "ADJA" :counter "1" } }
			{:word "duldsamer" {:pos "ADJA" :counter "1" } }
			{:word "vom" {:pos "APPRART" :counter "1" } }
			{:word "Verhörs" {:pos "NN" :counter "1" } }
			{:word "al-Arabi" {:pos "NE" :counter "1" } }
			{:word "von" {:pos "APPR" :counter "1" } }
			{:word "neuer" {:pos "ADJA" :counter "1" } }
			{:word "Damaskus" {:pos "NE" :counter "1" } }
			{:word "muß" {:pos "VMFIN" :counter "1" } }
			{:word "herangezogen" {:pos "VVPP" :counter "1" } }
			{:word "einstrich" {:pos "VVFIN" :counter "1" } }
			{:word "Staat" {:pos "NN" :counter "1" } }
			{:word "beklagen" {:pos "VVFIN" :counter "1" } }
			{:word "fragen" {:pos "VVINF" :counter "1" } }
			{:word "Schlager" {:pos "NN" :counter "1" } }
			{:word "sicher" {:pos "PTKVZ" :counter "1" } }
			{:word "ihre" {:pos "PPOSAT" :counter "1" } }
			{:word "Lebens" {:pos "NN" :counter "1" } }
			{:word "verfestigt" {:pos "VVPP" :counter "1" } }
			{:word "bewiesen" {:pos "VVPP" :counter "1" } }
			{:word "exiliert" {:pos "ADJD" :counter "1" } }
			{:word "Änderungen" {:pos "NN" :counter "1" } }
			{:word "anderen" {:pos "ADJA" :counter "1" } }
			{:word "Lehrer" {:pos "NN" :counter "1" } }
			{:word "Moschee" {:pos "NN" :counter "1" } }
			{:word "Zusätze" {:pos "NN" :counter "1" } }
			{:word "19." {:pos "ADJA" :counter "1" } }
			{:word "ganze" {:pos "ADJA" :counter "1" } }
			{:word "Reporter" {:pos "NN" :counter "1" } }
			{:word "besetzt" {:pos "VVPP" :counter "1" } }
			{:word "wünscht" {:pos "VVFIN" :counter "1" } }
			{:word "Nachrichtensendungen" {:pos "NN" :counter "1" } }
			{:word "Zustimmung" {:pos "NN" :counter "1" } }
			{:word "je" {:pos "ADV" :counter "1" } }
			{:word "laufenden" {:pos "NN" :counter "1" } }
			{:word "manchmal" {:pos "ADV" :counter "1" } }
			{:word "Seite" {:pos "NN" :counter "1" } }
			{:word "war" {:pos "VAFIN" :counter "1" } }
			{:word "Bericht" {:pos "NN" :counter "1" } }
			{:word "Gegensatz" {:pos "NN" :counter "1" } }
			{:word "Region" {:pos "NN" :counter "1" } }
			{:word "nichts" {:pos "PIS" :counter "1" } }
			{:word "stichhaltig" {:pos "ADJD" :counter "1" } }
			{:word "große" {:pos "ADJA" :counter "1" } }
			{:word "Homs" {:pos "NE" :counter "1" } }
			{:word "wegen" {:pos "APPR" :counter "1" } }
			{:word "Faustregel" {:pos "NN" :counter "1" } }
			{:word "Zeitungen" {:pos "NN" :counter "1" } }
			{:word "direkten" {:pos "ADJA" :counter "1" } }
			{:word "befreien" {:pos "VVINF" :counter "1" } }
			{:word "verließ" {:pos "VVFIN" :counter "1" } }
			{:word "ohne" {:pos "APPR" :counter "1" } }
			{:word "erteilt" {:pos "VVPP" :counter "1" } }
			{:word "Besitz" {:pos "NN" :counter "1" } }
			{:word "hin" {:pos "ADV" :counter "1" } }
			{:word "Untertänigkeit" {:pos "NN" :counter "1" } }
			{:word "Demokratie" {:pos "NN" :counter "1" } }
			{:word "wuchs" {:pos "VVFIN" :counter "1" } }
			{:word "später" {:pos "ADJD" :counter "1" } }
			{:word "Vorwürfe" {:pos "NN" :counter "1" } }
			{:word "Entfernung" {:pos "NN" :counter "1" } }
			{:word "ausgeliefert" {:pos "VVPP" :counter "1" } }
			{:word "unschuldig" {:pos "ADJD" :counter "1" } }
			{:word "Hama" {:pos "NE" :counter "1" } }
			{:word "Vor" {:pos "APPR" :counter "1" } }
			{:word "vertrieben" {:pos "VVPP" :counter "1" } }
			{:word "er" {:pos "PPER" :counter "1" } }
			{:word "der" {:pos "ART" :counter "1" } }
			{:word "meinen" {:pos "PPOSAT" :counter "1" } }
			{:word "syrischen" {:pos "ADJA" :counter "1" } }
			{:word "ich" {:pos "PPER" :counter "1" } }
			{:word "Herrschaft" {:pos "NN" :counter "1" } }
			{:word "d'Etat" {:pos "NN" :counter "1" } }
			{:word "begonnen" {:pos "VVPP" :counter "1" } }
			{:word "insgesamt" {:pos "ADV" :counter "1" } }
			{:word "strikter" {:pos "ADJA" :counter "1" } }
			{:word "sich" {:pos "PRF" :counter "1" } }
]))
